In [37]:
import random

a = []
b = []
for i in range(0,4):
    a.append([])
    b.append([])
    for j in range(0,4):
        val = random.randint(0,100)
        val1 = random.randint(0,100)
        a[i].append(val)
        b[i].append(val1)
print("Mang a la: " , a)
print("Mang b la: " , b)

Mang a la:  [[24, 60, 95, 34], [29, 37, 15, 57], [28, 73, 17, 88], [92, 71, 1, 51]]
Mang b la:  [[86, 74, 94, 92], [6, 41, 76, 10], [14, 20, 23, 96], [86, 52, 35, 0]]


In [38]:
import random

a = []
b = []
c = []
for i in range(0,4):
    a.append([])
    b.append([])
    c.append([])
    for j in range(0,4):
        val = random.randint(0,100)
        val1 = random.randint(0,100)
        a[i].append(val)
        b[i].append(val1)
        c[i].append(val+val1)
print("Mang a la: " , a)
print("Mang b la: " , b)
print("Mang a + b la: " , c)

Mang a la:  [[90, 98, 32, 99], [39, 93, 13, 10], [66, 27, 78, 20], [14, 29, 88, 69]]
Mang b la:  [[13, 27, 22, 5], [79, 40, 6, 34], [17, 27, 22, 3], [96, 93, 54, 30]]
Mang a + b la:  [[103, 125, 54, 104], [118, 133, 19, 44], [83, 54, 100, 23], [110, 122, 142, 99]]


In [162]:
import random
import time

start_time = time.time()
a = []
b = []
resultA = 0
resultB = 0
lengA = 0
lengB = 0
for i in range(0,4):
    a.append([])
    b.append([])
    for j in range(0,4):
        val = random.randint(0,100)
        resultA += val
        val1 = random.randint(0,100)
        resultB += val1
        a[i].append(val)
        lengA += 1
        b[i].append(val1)
        lengB += 1
resultA /= lengA
resultB /= lengB
end_time = time.time()
print("Mang a la: " , a)
print("Mang b la: " , b)
print('Trung binh cac phan tu trong mang a la: ' , resultA)
print('Trung binh cac phan tu trong mang a la: ' , resultB)
print('Tong thoi gian thuc hien: %fs' % (end_time - start_time))


Mang a la:  [[56, 41, 18, 14], [21, 60, 95, 68], [91, 45, 71, 30], [19, 76, 39, 95]]
Mang b la:  [[49, 9, 31, 36], [45, 27, 95, 89], [82, 50, 70, 41], [82, 37, 31, 31]]
Trung binh cac phan tu trong mang a la:  52.4375
Trung binh cac phan tu trong mang a la:  50.3125
Tong thoi gian thuc hien: 0.001202s


In [163]:
import numpy as np
import time

start_time = time.time()
a = np.random.randint(100,size=(4,4))
b = np.random.randint(100,size=(4,))
print("Mang a la:\n " , a)
print("Mang b la:\n " , b)
resultA = np.mean(a)
resultB = np.mean(b)
end_time = time.time()
print('Trung binh cac phan tu trong mang a la: ' , resultA)
print('Trung binh cac phan tu trong mang a la: ' , resultB)
print('Tong thoi gian thuc hien: %fs' % (end_time - start_time))

Mang a la:
  [[50 65 54 97]
 [ 5  4 50 95]
 [80 26 48 70]
 [88  2 39 47]]
Mang b la:
  [15 71 45 29]
Trung binh cac phan tu trong mang a la:  51.25
Trung binh cac phan tu trong mang a la:  40.0
Tong thoi gian thuc hien: 0.001002s


In [132]:
def SimpleSumArray(a):
    sum = 0
    for element in a:
        sum+=element
    return sum
def result(a):
    sum = 0
    for element in a:
        sum+=element
    return sum
#SumArray(a)
#print(SumArray(a))
print(result(SumArray(a)))

# cách thường dùng
sum = 0
for i in range(len(a)):
    for j in range(len(a)):
        sum += a[i][j]
print("Tong cua mang la: ", sum)

686
Tong cua mang la:  686


In [133]:
import numpy as np
print("Tong cua mang khi dung numpy: ", np.sum(a))

Tong cua mang khi dung numpy:  686


In [187]:
import numpy as np
import time

start_time = time.time()
print("MAX = ",np.max(a))
print("MiN = ", np.min(a))
end_time = time.time()
print('Tong thoi gian thuc hien: %fs' % (end_time - start_time))

MAX =  97
MiN =  2
Tong thoi gian thuc hien: 0.000990s


In [180]:
import time

start_time = time.time()
max= -10**9
min = 10**9
for i in range(len(a)):
    for j in range(len(a)):
        if max<a[i][j]:
            max = a[i][j]
        if min>a[i][j]:
            min = a[i][j]
end_time = time.time()
print("MAX = ",max)
print("MIN = ",min)
print('Tong thoi gian thuc hien: %fs' % (end_time - start_time))

MAX =  97
MIN =  2
Tong thoi gian thuc hien: 0.001001s
